/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presupuestoefectivo;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.logging.*;
import base.Conexionyfunciones;
/**
 *
 * @author Daniel
 */
public class Reportetablas2 extends javax.swing.JFrame {

    DefaultTableModel Tablaing;   
    String ing[]={"idEmpresa","Periodo","preciovenunidad","ventaenunidades","ventaefectivo", "cantcobromes","cantcobromesant","cantcobro2meses","Total ing"};
    String egr[]={"idEmpresa","Periodo","costounitariomano","costoadminuni","costoventasuni","costomanototal","iva","gastosadmin","gastosventas","prestamo","gastosfin","impuestos","total"};
    String flujo[]={"id Empresa", "Perdiodo", "totIng","totegr","flujoneto","saldo inicial","saldo final","Financiamiento"},nombre;
    String balance[]={"idEmpresa","idPeriodo","efectivo","cuentas_cobrar","activocirtotal","equipodereparto","depresionac","totactivosfijos","totalactivos","Pasivos","capitalsocial","Utilidad acumuladad","capitaltotal","Pasmascap"};
   
    
    Conexionyfunciones obj;
    /*
     * Creates new form Reportetablas
     */
    public Reportetablas2(int id,String nombre) {
        this.nombre=nombre;
        Tablaing= new DefaultTableModel(null,balance){
    @Override
    public boolean isCellEditable (int fila, int columna) {
        return false;
    }};
        obj=new Conexionyfunciones();
        obj.conectar();
        obj.datosTabla(id, Tablaing,"empresa_balance");
        initComponents();    
        
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
         setBounds(400, 0, 750, 300);
         this.setLocationRelativeTo(this);
    }
    
    
    
   
      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText(nombre);

        jLabel2.setText("Balance");

        jTable2.setModel(Tablaing);
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(173, 173, 173))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(39, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(485, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(344, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
